#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier		super
bspc config pointer_action1			move
bspc config pointer_action2			resize_side
bspc config pointer_action3			resize_cirnoer

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/polybar/launch.sh &
nm-applet &
pa-applet &
picom &
python -m pywal -i w/bg.jpg &
